import React from 'react';
import Head from 'next/head';

import Footer from './Footer';
import Banner from './Banner';

const Layout = ({ children }) => {
  return (
    <div className='layout'>
      <Head>
        <title>Aduke E-menu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <Banner />
      </header>
      <main className='main-container'>{children}</main>
      <footer>
        <Footer />
      </footer>
    </div>
  );
};

export default Layout;
